sudo: false
language: node_js
node_js:
  - "5.0"
  - "4.0"
  - "0.12"
  - "0.10"


# Make sure we have new NPM.
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
  - npm config set loglevel warn
