sudo: false
language: node_js
node_js:
  - 6
  - 8
  - 10

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
