sudo: false
language: node_js
node_js:
  - 8
  - 10

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - xvfb

# Make sure we have new NPM.
before_install:
  - export DISPLAY=:99.0
  - npm install -g npm
  - npm config set loglevel warn
